1) List slicing: Run the cell below 

In [4]:
list_nums = [3,6,9,13,47,101,102,104,105,200,301]

a) print the whole list

In [5]:
list_nums[:]

[3, 6, 9, 13, 47, 101, 102, 104, 105, 200, 301]

b) print all numbers from 13 to 200

In [6]:
list_nums[3:10]

[13, 47, 101, 102, 104, 105, 200]

c) print the list in reverse

In [15]:
list_nums[::-1]

[301, 200, 105, 104, 102, 101, 47, 13, 9, 6, 3]

d) extract numbers 3 to 104, missing out every other number (e.g. 3, 9, 47, 102). Save this in a new variable and then print it

In [16]:
list_nums[:]

[3, 6, 9, 13, 47, 101, 102, 104, 105, 200, 301]

In [18]:
new_list_nums =list_nums[0:8:2]
print(new_list_nums)

[3, 9, 47, 102]


Run the cell below

In [15]:
sentence = "Hello, I like christmas trees!"

e) print just "christmas trees" from the variable 'sentence'

In [18]:
sentence[14:29]

'christmas trees'

f) print the full sentence but in reverse

In [19]:
sentence[::-1]

'!seert samtsirhc ekil I ,olleH'

Bonus: Below is a matrix. In a previous lecture we touched on lists within lists.
This is a very important concept in Machine Learning. Below is a matrix (lists, within lists, within lists). 
Here is a list within a list: 

In [21]:
#Run this cell
list_list = [[1,2,3],[4,5,6]]

To extract either of the lists you can just use list_list[0] or list_list[1]. But to extract a number from a list, e.g. 
the number 4 you would first extract the second list with list_list[1] and then immediately after [0], so it looks like this: 
list_list[1][0]. Try it below (run the cell above first)

In [23]:
list_list[1][0] #Remeber indexes start with 0, so 1 is really the second matrix.

4

Try it yourself now with a matrix (hint to extract just a number you will need to do matrix[][][]!)

Run the cell below:

In [20]:
matrix = [[[1,5,2,0.5],[0.2,0.7,19,299]],[[0.11,13,15.7,19,20],[1,0.1,0.01,0.2,20,23,1000]]]

g) print out the first two list (keep in mind they are within the same list - [[1,5,2,0.5],[0.2,0.7,19,299]])

In [21]:
matrix[0]

[[1, 5, 2, 0.5], [0.2, 0.7, 19, 299]]

h) print out just the first list

In [37]:
matrix[0][0]

[1, 5, 2, 0.5]

i) print out the number 19 1000 from matrix

In [71]:
print(matrix[1][0:2][0][3], matrix[1][1][6])

19 1000


2) Sets and tuples

a) Turn the list below into a set (make sure to run the cell to create the variable):

In [75]:
List_names = ["Jim","Jackie","Harry","Jim","Hywel","Jackie","Hywel"]

b) What is one of the main purposes of sets?

In [22]:
#to display/output data without repetitions of elements while/if they are present.
#Provides only unique elements

In [77]:
set(List_names)

{'Harry', 'Hywel', 'Jackie', 'Jim'}

c) How is a tuple different to a list?

In [24]:
#Tuples are immutable, elements within a tuple cannot be modified/altered

3) Dictionaries

a) Create a dictionary below with five different key-value pairs. Hint {key:value, key2:value}

In [30]:
dic={"Ben":50,"Roger":100,"Gerald":15,"Retardo":0,"Janet":1000} #DICTIONARIES CAN BE KEPT IN ANY ORDER

In [31]:
dic

{'Ben': 50, 'Gerald': 15, 'Janet': 1000, 'Retardo': 0, 'Roger': 100}

b) Add a new key-value pair to your dictionary

In [32]:
dic["Jennifer"] = 50

In [33]:
dic

{'Ben': 50,
 'Gerald': 15,
 'Janet': 1000,
 'Jennifer': 50,
 'Retardo': 0,
 'Roger': 100}

c) Print just one key-value pair from the dictionary

In [102]:
dic["Ben"]

50

d) change the values of our of your keys

In [108]:
dic["Ben"] += 50

In [109]:
dic

{'Ben': 100,
 'Gerald': 15,
 'Janet': 1000,
 'Jennifer': 50,
 'Retardo': 0,
 'Roger': 100}